services:
  user-service:
    build:
      target: development
    command: npm run dev
    volumes:
      - ./user-service:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app

  payment-service:
    build:
      target: development
    command: npm run dev
    volumes:
      - ./payment-service:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app

  product-service:
    build:
      target: development
    command: npm run dev
    volumes:
      - ./product-service:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app

  tombola-service:
    build:
      target: development
    command: npm run dev
    volumes:
      - ./tombola-service:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app

  settings-service:
    build:
      target: development
    command: npm run dev
    volumes:
      - ./settings-service:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app

  notification-service:
    build:
      target: development
    command: npm run dev
    volumes:
      - ./notification-service:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app

  chat-service:
    build:
      target: development
    command: npm run dev
    volumes:
      - ./chat-service:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app

  admin-frontend-ms:
    build:
      context: ./admin-frontend-ms
      target: builder
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "80"]
    volumes:
      - ./admin-frontend-ms:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app

